name: Reviewdog
on:
  pull_request:
    branches: [main]

jobs:
  actionlint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: reviewdog/action-actionlint@v1
        with:
          # Disable shellcheck to prevent false positive about powershell scripts
          actionlint_flags: -shellcheck=
          filter_mode: nofilter
  yamllint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: reviewdog/action-yamllint@v1
        with:
          filter_mode: nofilter
